FROM node:16

WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy application code
COPY . .

# Define environment variable
ENV REACT_APP_BACKEND_URL=http://0.0.0.0:8000

EXPOSE 3000

CMD ["npm", "start"]
